LeahWinters/rancidTomatillos

src/App/App.css
src/App/App.js
src/MoviesContainer/MoviesContainer.css
src/MoviesContainer/MoviesContainer.js
src/NavBar/NavBar.css
src/apiCalls.js
src/movieCard/movieCard.css
src/movieCard/movieCard.js

- Completed by both Justin and I
- Fetched all movies
- Added functionality to display all movies
- Added basic styling to the movie cards, movie container, and nav bar
The beginning stages of creating a functioning  application.
None.

Display movies

---

src/App/App.js
src/Login/Login.js
src/NavBar/NavBar.js
src/index.js
src/movieCard/movieCard.js

-Completed as a team
-Added functionality to the login button in the NavBar, when clicked, it brings user to a login page
Adds functionality so they user can login.
none.

Login page functionality

---

package-lock.json
package.json
src/App/App.css
src/MoviesContainer/MoviesContainer.css
src/NavBar/NavBar.css
src/NavBar/NavBar.js
src/movieCard/MovieCard.css
src/movieCard/MovieCard.js

Styled the movie page using css.
To make the application more pleasing to look at.
none.

Style movie page

---

src/Login/Login.css
src/MoviesContainer/MoviesContainer.js

styling for the login page. 
Changing the background for the page has a some weird header where the image doesn't fill. I'm thinking about putting the image into the html/jsx

add styling for login page

---

src/Login/Login.css
src/MoviesContainer/MoviesContainer.js
src/NavBar/NavBar.css
src/NavBar/NavBar.js

Fixed some small styling on login page and nav bar, as a result of merges.
Makes application look as we want it to.
none

Fix small styling issues

---

src/App/App.js
src/Login/Login.css
src/Login/Login.js
src/apiCalls.js

- Completed as a team
- Added functionality so when the user fills out login form, a post is made
- If login is incorrect, an error is displayed telling user what went wrong
Adds functionality to the login page, allows a user to correctly log in and if they do not correctly login, they are directed to change what went wrong. Allows for a better user experience.
Getting post to work correctly. After looking farther into postman post, we realized we were missing a header.

Add functionality to login page, the fetch call to post a login, and error message

---

src/App/App.js
src/Login/Login.js
src/NavBar/NavBar.js

- When the user is logged in, the navbar's button says 'logout'
- When the user clicks 'logout', the user is brought back to the home page.
So the user can log out and see that they are logged out.
The url when the user is brought back to the home page is incorrect. Currently it shows '/user-movie-page' when the user logs out, but it is displaying the correct page.  The url should be just '/', when the user logs out. I think it's a Router issue, but I'm honestly not sure how to fix it. I plan on reaching out for help tomorrow to mod4/the instructors.

Logout functionality

---

src/App/App.css
src/App/App.js
src/NavBar/NavBar.js

Removed an import or Redirect where not needed and added a new class name to a rendered component in hopes to help with previous PR's issue. Still not able to get the correct URL when user logs out.
Cleans up code
Still not able to get the correct URL when user logs out. I messaged Khalid all of the code in hopes that he can help show me what I am doing wrong. After todays lesson, I feel it's probably something small that I just can't see.

Small clean up

---

src/movieCard/MovieCard.css
src/movieCard/MovieCard.js

Added a button to the movie card when user is logged in to be used in next feature so that the user can click to view each movies details.
So that the user can expand and see a specific movies details.
none.

Add btn to movie cards when user is logged in

---

src/MovieDetails/MovieDetails.js

wrapped function in component did mount

add component did mount

---

src/App/App.css
src/App/App.js
src/MovieDetails/MovieDetails.css
src/MovieDetails/MovieDetails.js
src/MoviesContainer/MoviesContainer.js
src/RateMovieForm/RateMovieForm.css
src/RateMovieForm/RateMovieForm.js
src/apiCalls.js
src/movieCard/MovieCard.css
src/movieCard/MovieCard.js

- All movie details now display on individual move detail page
- User can also see a form on the movie details page
- Whole page is styled.
- For more user interaction
I was trying to separate the movie genres with commas and a space, but I kept getting an error saying that the array prototypes of split and join are undefined. I googled for awhile, but was unable to get the array split like I wanted. Will come back to later.

Display movie details

---

src/App/App.css
src/Login/Login.css
src/Login/Login.js
src/MovieDetails/MovieDetails.css
src/MoviesContainer/MoviesContainer.js
src/RateMovieForm/RateMovieForm.css

Tried to get the login to have a background image but there is a weird bug taking up a chunk of the top of the page, so I commented out the image. I then put all css elements properties into alphabetical order to make it easier to read.
Clean code = beautiful code!

Try to fix login background and put all css elements in alphabetical order

---

src/App/App.js
src/Login/Login.js
src/apiCalls.js

fetches rating data for a user once they log In
yes- have to await for state to change before invoking.

got rating fetch call to send back data

---

src/App/App.js
src/MovieDetails/MovieDetails.js
src/MoviesContainer/MoviesContainer.js
src/RateMovieForm/RateMovieForm.js
src/apiCalls.js

hooked up post call for submitting rating

add post call to submit rating

---

src/App/App.js
src/Login/Login.js
src/MovieDetails/MovieDetails.css
src/MovieDetails/MovieDetails.js
src/MoviesContainer/MoviesContainer.js
src/movieCard/MovieCard.js

Added functionality so that when the user logs in, they see which movies they have already rated on the movie card.
So that the user knows if they should rate the movie or not.
Struggled to grasp out to get this part working, after 3 hours on it I finally got it.

Display user rating

---

src/App/App.js
src/Login/Login.css
src/Login/Login.js
src/MovieDetails/MovieDetails.js
src/RateMovieForm/RateMovieForm.css
src/RateMovieForm/RateMovieForm.js
src/apiCalls.js
src/movieCard/MovieCard.js

get rating to display on details page
- add function to find rating from users ratings
- pass props in right places
changed log in button to submit so you can press enter or click to login
rounded average rating everywhere t a whole number
add functionality to delete rating
-api call
-conditional rendering to show a delete button if they have rated a movie 
- or show a form if they havent rated a movie
also fixed some styling on the login page
* tried to get the movie details page to link back to the home page but it didn't work *

get rating to display on details page

---

src/MovieDetails/MovieDetails.js
src/MoviesContainer/MoviesContainer.js
src/RateMovieForm/RateMovieForm.js

Added functionality to the 'view all movies' button located on the movie detail page, by adding a <Link> around the button.
So the user can go back to looking at all of the movies once they are done looking at a specific movies details.
None.

View All Movies Button

---

package-lock.json
package.json
src/App/App.test.js
src/Login/Login.test.js
src/MovieDetails/MovieDetails.test.js
src/NavBar/NavBar.test.js
src/RateMovieForm/RateMovieForm.test.js
src/movieCard/MovieCard.test.js

Still working on this branch, pushed up so our instructor can view code and see if they have an issue with waitFor.
Also added some tests to the login.test.js, NavBar.test.js, RateMovieForm.test.js files and tried to test the MovieDetails.test.js file but will have to come back to it.

Moved test to app.test file

---

src/App/App.css
src/App/App.js
src/App/App.test.js
src/Login/Login.css
src/Login/Login.js
src/Login/Login.test.js
src/MovieDetails/MovieDetails.js
src/MovieDetails/MovieDetails.test.js
src/MoviesContainer/MoviesContainer.js
src/MoviesContainer/MoviesContainer.test.js
src/NavBar/NavBar.js
src/RateMovieForm/RateMovieForm.css
src/RateMovieForm/RateMovieForm.js
src/RateMovieForm/RateMovieForm.test.js
src/apiCalls.js
src/movieCard/MovieCard.test.js

Added a couple of integration and async tests to test the app component. Also went through every file and cleaned up all of the code: got ride of extra white space, console.logs, and unused items in the code base.
To make sure that the user interaction is going as we expect.
Getting console.logs to work correctly in a test file. Still have not figured it out, but I plan on doing some research on it.

Add more tests in app.test.js and cleaned up the code in all files

---

package.json
src/Login/Login.js
src/MovieDetails/MovieDetails.js
src/MoviesContainer/MoviesContainer.js
src/movieCard/MovieCard.js

add prop types to most of the child components
type checking of pass props

add prop types to most of the child components
